# Generated by Django 5.2.10 on 2026-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_restotable"),
    ]

    operations = [
        migrations.AddField(
            model_name="restotable",
            name="qr_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
