# Generated by Django 5.2.10 on 2026-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_restotable_qr_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restotable",
            name="qr_token",
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
