# Generated by Django 5.2.10 on 2026-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_restotable_qr_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="restotable",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restotable",
            name="table_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Table Number"
            ),
        ),
    ]
