# Generated by Django 5.2.10 on 2026-01-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_restotable_is_active_restotable_table_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restotable",
            options={},
        ),
        migrations.AddConstraint(
            model_name="restotable",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "table_number"),
                name="unique_table_number_per_restaurant",
            ),
        ),
    ]
