# Generated by Django 5.2.10 on 2026-01-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menucategory",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ("-created_at",)},
        ),
    ]
