# Generated by Django 5.2.10 on 2026-01-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.FloatField(
                blank=True,
                default=True,
                null=True,
                verbose_name="is this order is active",
            ),
        ),
    ]
