# Generated by Django 5.2.10 on 2026-01-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_active",
        ),
    ]
