# Generated by Django 5.2.10 on 2026-01-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Is this order active?"
            ),
        ),
    ]
